### ISSUE TITLE
Exceptional.map(...) should accept `ExceptionalFunction` 

### ISSUE THREAD

**Issue by tchudyk** [romangr/exceptional#10]
It would be nice if we could handle/wrap exceptions during mapping in `Exceptional`.

For example, we have (in some class) method with signature `Exceptional<Path> getPath(String fileId)` and we could handle it as:
```java
return myRepository.getPath(fileId)
   .map(path -> {
        return Files.readAllBytes(path);
   });
```
Currently `Files.readAllBytes` throws IOException, and we need it to handle it manually inside `map` method.

**Comment by romangr** [comment]
In this case `safelyMap(...)` method can be used
https://github.com/romangr/exceptional/blob/master/src/main/java/ru/romangr/exceptional/Exceptional.java#L130

**Comment by romangr** [comment]
I see your point, safelyMap actually should accept `ExceptionalFunction`

**Comment by romangr** [comment]
Fixed in https://github.com/romangr/exceptional/pull/11
