### ISSUE TITLE
Add method Exceptional.of(...)

### ISSUE THREAD

**Issue by tchudyk** [romangr/exceptional#9]
I can see in API there are methods:
`Exceptional.getExceptional(...)` and `Exceptional.exceptional(...)`.

I think it will be more readable if we could replace this methods with:
`Exceptional.of(V value)`, `Exceptional.of(Exception exception)` and `Exceptional.of(ExceptionalSupplier supplier)` - it is like with java buildin `Optional<T>` type.

Or some other short names like: `Exceptional.ok(V value)`, `Exceptional.err(Exception...)`, `Exceptional.attempt(ExceptionalSupplier supplier)`

**Comment by romangr** [comment]
Good point, I'll think about it

**Comment by romangr** [comment]
Fixed at https://github.com/romangr/exceptional/pull/11
